# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt \
    && pip install apache-beam

COPY . /app/

# Create the output directory
RUN mkdir /app/output

CMD ["python", "./stream_processing_pipeline.py"]

